Ext.define("catcher.view.HelpPanel",{
	extend: "Ext.Panel",
	xtype: "helpPanel",
	requires: ['Ext.TitleBar'],	
	
	config:{
		title: "Nápověda",
		iconCls: "help",
		styleHtmlContent: true,
    	fullscreen: true,
    	scrollable: {
			direction: 'vertical',
			directionLock: true
		},
		items:[{
				xtype: "titlebar",
				title: "Nápověda",
				docked: "top"
			}
		],
		
		html: [      
"<h3>Návod pro týmy</h3>",
"<strong>Vlastní tým(y) během turnaje</strong>",
"<ul>",
"<li>Aplikaci lze využít jako přenosný rozpis pro svůj tým (menu - filtr týmu)</li>",
"<li>V hlavní liště dole je ikonka Spirit pro zadání Spiritu. Mimo standardního Spirit Sheetu lze údaje zadat i sem, ulehčíte tak organizátorům sčítání a minimalizují se možné nepřesnosti.</li>",
"<li>Zadaný spirit je veřejně viditelný až po ukončení turnaje.</li>",
"<li>Pokud je na turnaji více týmů jednoho oddílu, vždy se při vstupu do Spiritu zvolí tým, kterému se Spirit zadává.</li>",
"</ul>",
"<strong>Soupiska týmu</strong>",
"<ul>",
"<li>Vlastní soupisku je možné upravit (změnit číslo hráče, jméno, připojit nové hráče pro turnaj) pomocí ikonky Hráči v navigační liště dole.</li>",
"<li>Přezdívky a čísla hráčů lze upravit (pouze u svého týmu). Data jsou globální pro všechny turnaje!</li>",
"<li>Soupisky ostatních týmů lze jen prohlížet.</li>",
"<li>Nového hráče lze na turnaj připojit přes ikonku vpravo nahoře na Soupisce týmu.</li>",
"<li>Lze připojit hráče na \"hostování\" z jiného týmu. Pomocí hledací ikonky, a vyhledání dle jména či přezdívky. Hráč nesmí na turnaji již hrát!</li>",
"<li>Úplně nového hráče nelze přidat v aplikaci, každý hráč by měl být v Evidenci ČALD.</li>",
"</ul>",
"<h3>Návod organizátory</h3>",
"<strong>Parametry turnaje</strong>",
"<ul>",
"<li>V panelu Organizátor je možné změnit názvy skupin (doplnit chybějící), doplnit čísla hřišť, změnit výchozí délku utkání (typicky rozdílné časy v neděli oproti sobotě)</li>",
"<li>Turnaj lze i přejmenovat či změnit jeho popisek</li>",
"</ul>",
"<strong>Přepínače turnaje</strong>",
"<ul>",
"<li>Aktivní - k turnaji je možné se přihlásit z této aplikace; pozor: při deaktivaci se již nebude možné po odhlášení znovu přihlásit</li>",
"<li>Ukončený - turnaj se přestane zobrazovat na titulce frisbee.cz a začne se zobrazovat zadaný Spirit of the Game</li>",
"<li>TOP 10 - zobrazovat statistiky pro 10 nejproduktivnějších hráčů?</li>",
"<li>Spirit - zobrazovat po Ukončení turnaje zadaný Spirit of the Game?</li>",
"</ul>",
"<strong>Skórování zápasu</strong>",
"<ul>",
"<li>Časomíru lze odstartovat přes Menu ručně, jinak bude start nastaven dle času v rozpisu po zadání prvního bodu.</li>",
"<li>Zadané body lze upravit či smazat přes tlačítko Zobrazit vložené body.",
"<li>Po konci zápasu v sekci Nastavení přepnout \"Zápas skončil\".",
"<li>Lze zadat ručně (v Menu - Nastavení zápasu) skóre vyšší, než je stávající. Vygenerované body budou anonymní.",
"<li>Možnost rychlého přístup k nastavení a celkovému skóre utkání pomocí podržení prstu na seznamu zápasů</li>",
"</ul>",
"<strong>Správa Spiritu</strong>",
"<ul>",
"<li>Organizátor turnaje může zadat Spirit za kterýkoliv tým a vidí všechny zadané SotG.</li>",
"<li>V Menu sekce Spirit jsou volby na zobrazení seznamu nezadaných Spiritů a také průběžných/konečných výsledků.</li>",
"</ul>",
"<strong>Chybějící zápasy</strong>",
"<ul>",
"<li>Zápasy, které nejsou v aplikaci (play-off) je nutné vytvořit přes Menu - Přidat nové utkání. Je nutné vybrat typ zápasu a vhodné je nastavit začátek dle rozpisu</li>",
"<li>Nesprávně zadané zápasy lze smazat přes rychlé menu zápasu (podržením prstu na zápasu v seznamu)",
"</ul>",
"<strong>Online přístup</strong>",
"<ul>",
"<li>Aplikace musí být při používání online. Pokud nebude, nepůjde ukládat body. Datový přenos je v řádu desítek kB/zápas.</li>",
"<li>Díky neustálé synchronizaci dat je možné skórovat jeden zápas z více zařízení</li>",
"<li>Výstup z aplikace (průběhy zápasů, tabulky) jsou k dispozici na www.frisbee.cz/online-vysledky.html</li>",
"</ul>"
].join("")		
	}				
});